package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"

	"github.com/sonicfromnewyoke/mithril/pkg/sbpf"
)

type syscallDef struct {
	name     string
	function string
	feature  string
}

func main() {
	syscallDefs := []syscallDef{
		{"abort", "SyscallAbort", ""},
		{"sol_panic_", "SyscallPanic", ""},
		{"sol_log_", "SyscallLog", ""},
		{"sol_log_64_", "SyscallLog64", ""},
		{"sol_log_pubkey", "SyscallLogPubkey", ""},
		{"sol_log_compute_units_", "SyscallLogCUs", ""},
		{"sol_log_data", "SyscallLogData", ""},
		{"sol_sha256", "SyscallSha256", ""},
		{"sol_keccak256", "SyscallKeccak256", ""},
		{"sol_blake3", "SyscallBlake3", "ft.IsActive(features.Blake3SyscallEnabled)"},
		{"sol_secp256k1_recover", "SyscallSecp256k1Recover", ""},
		{"sol_big_mod_exp", "SyscallBigModExp", "ft.IsActive(features.EnableBigModExpSyscall)"},
		{"sol_poseidon", "SyscallPoseidon", ""},
		{"sol_remaining_compute_units", "SyscallRemainingComputeUnits", "ft.IsActive(features.RemainingComputeUnitsSyscallEnabled)"},
		{"sol_curve_validate_point", "SyscallValidatePoint", "ft.IsActive(features.Curve25519SyscallEnabled)"},
		{"sol_curve_multiscalar_mul", "SyscallCurveMultiscalarMultiplication", "ft.IsActive(features.Curve25519SyscallEnabled)"},
		{"sol_curve_group_op", "SyscallCurveGroupOps", "ft.IsActive(features.Curve25519SyscallEnabled)"},
		{"sol_curve_decompress", "SyscallCurveDecompress", "ft.IsActive(features.EnableBls12_381Syscall)"},
		{"sol_curve_pairing_map", "SyscallCurvePairingMap", "ft.IsActive(features.EnableBls12_381Syscall)"},
		{"sol_alt_bn128_compression", "SyscallAltBn128Compression", "ft.IsActive(features.EnableAltbn128CompressionSyscall)"},
		{"sol_alt_bn128_group_op", "SyscallAltBn128", "ft.IsActive(features.EnableAltBn128Syscall)"},
		{"sol_memcpy_", "SyscallMemcpy", ""},
		{"sol_memcmp_", "SyscallMemcmp", ""},
		{"sol_memset_", "SyscallMemset", ""},
		{"sol_memmove_", "SyscallMemmove", ""},
		{"sol_alloc_free_", "SyscallAllocFree", "!isDeploy"},
		{"sol_create_program_address", "SyscallCreateProgramAddress", ""},
		{"sol_try_find_program_address", "SyscallTryFindProgramAddress", ""},
		{"sol_get_stack_height", "SyscallGetStackHeight", ""},
		{"sol_get_return_data", "SyscallGetReturnData", ""},
		{"sol_set_return_data", "SyscallSetReturnData", ""},
		{"sol_get_processed_sibling_instruction", "SyscallGetProcessedSiblingInstruction", ""},
		{"sol_get_clock_sysvar", "SyscallGetClockSysvar", ""},
		{"sol_get_rent_sysvar", "SyscallGetRentSysvar", ""},
		{"sol_get_epoch_schedule_sysvar", "SyscallGetEpochScheduleSysvar", ""},
		{"sol_get_epoch_rewards_sysvar", "SyscallGetEpochRewardsSysvar", "ft.IsActive(features.EnablePartitionedEpochReward) || ft.IsActive(features.EnablePartitionedEpochRewardsSuperfeature)"},
		{"sol_get_last_restart_slot", "SyscallGetLastRestartSlotSysvar", "ft.IsActive(features.LastRestartSlotSysvar)"},
		{"sol_invoke_signed_c", "sbpf.SyscallFunc5(SyscallInvokeSignedCImpl)", ""},
		{"sol_invoke_signed_rust", "sbpf.SyscallFunc5(SyscallInvokeSignedRustImpl)", ""},
		{"sol_get_sysvar", "SyscallGetSysvar", "ft.IsActive(features.GetSysvarSyscallEnabled)"},
		{"sol_get_epoch_stake", "SyscallGetEpochStake", "ft.IsActive(features.EnableGetEpochStakeSyscall)"},
	}

	// syscallComments are emitted verbatim above the corresponding case in
	// the generated Syscalls switch.
	syscallComments := map[string]string{
		"sol_big_mod_exp": `// PINNED to the agave-syscalls-4.0.0 / solana-big-mod-exp-3.0.0
// implementation this fork targets. The gate
// EBq48m8irRKuE7ZnMTLvLg2UuGSqhe8s8oMqnmja1fJw is inactive on mainnet as of
// 2026-07, but agave master has replaced the body with an Ok(1) no-op stub
// pending SIMD-0529: if this gate ever activates on mainnet, the
// implementation behind SyscallBigModExp MUST be revisited before the
// activation epoch or the node will fork. See the comment on
// SyscallBigModExpImpl in syscalls_big_mod_exp.go.
`,
	}

	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "Usage: %s <filename>\n", os.Args[0])
		os.Exit(1)
	}

	// Check if there are hash collisions
	{
		collided := false
		hashToSyscall := make(map[uint32]string, len(syscallDefs))
		for _, s := range syscallDefs {
			h := sbpf.SymbolHash(s.name)
			prev, exists := hashToSyscall[h]
			if exists {
				collided = true
				fmt.Fprintf(os.Stderr, "%s and %s had the same SymbolHash: %x\n", prev, s.name, h)
			}
		}
		if collided {
			os.Exit(1)
		}
	}

	buf := &bytes.Buffer{}
	fmt.Fprintln(buf,
		`// Code generated by syscalls_gen syscalls.go or go generate. Manual edits may be overwritten.

package sealevel

import (
	"github.com/sonicfromnewyoke/mithril/pkg/features"
	"github.com/sonicfromnewyoke/mithril/pkg/sbpf"
)

const (`)

	for _, s := range syscallDefs {
		fmt.Fprintf(buf, "hash_%s = 0x%x\n", s.name, sbpf.SymbolHash(s.name))
	}

	fmt.Fprintln(buf, `)

func Syscalls(ft *features.Features, isDeploy bool, h uint32) (f sbpf.Syscall, ok bool) {
	ok = true
	switch h {`)

	for _, s := range syscallDefs {
		if comment, ok := syscallComments[s.name]; ok {
			fmt.Fprint(buf, comment)
		}
		fmt.Fprintf(buf, "case hash_%s:\n", s.name)
		fmt.Fprintf(buf, "f = %s\n", s.function)
		if s.feature != "" {
			fmt.Fprintf(buf, "ok = %s\n", s.feature)
		}
	}

	fmt.Fprintln(buf, `default:
ok = false
}
return
}`)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error formatting file: %v\n", err)
		os.Exit(1)
	}

	filename := os.Args[1]
	if err := os.WriteFile(filename, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing file: %v\n", err)
		os.Exit(1)
	}
}
