// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: txn_v2.proto

package conformance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxnFeatureSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []uint64               `protobuf:"fixed64,1,rep,packed,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnFeatureSet) Reset() {
	*x = TxnFeatureSet{}
	mi := &file_txn_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnFeatureSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnFeatureSet) ProtoMessage() {}

func (x *TxnFeatureSet) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnFeatureSet.ProtoReflect.Descriptor instead.
func (*TxnFeatureSet) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{0}
}

func (x *TxnFeatureSet) GetFeatures() []uint64 {
	if x != nil {
		return x.Features
	}
	return nil
}

type TxnAcctState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Lamports      uint64                 `protobuf:"varint,2,opt,name=lamports,proto3" json:"lamports,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Executable    bool                   `protobuf:"varint,4,opt,name=executable,proto3" json:"executable,omitempty"`
	Owner         []byte                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnAcctState) Reset() {
	*x = TxnAcctState{}
	mi := &file_txn_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnAcctState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnAcctState) ProtoMessage() {}

func (x *TxnAcctState) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnAcctState.ProtoReflect.Descriptor instead.
func (*TxnAcctState) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{1}
}

func (x *TxnAcctState) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *TxnAcctState) GetLamports() uint64 {
	if x != nil {
		return x.Lamports
	}
	return 0
}

func (x *TxnAcctState) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TxnAcctState) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

func (x *TxnAcctState) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

type TxnFixtureMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FnEntrypoint  string                 `protobuf:"bytes,1,opt,name=fn_entrypoint,json=fnEntrypoint,proto3" json:"fn_entrypoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnFixtureMetadata) Reset() {
	*x = TxnFixtureMetadata{}
	mi := &file_txn_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnFixtureMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnFixtureMetadata) ProtoMessage() {}

func (x *TxnFixtureMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnFixtureMetadata.ProtoReflect.Descriptor instead.
func (*TxnFixtureMetadata) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{2}
}

func (x *TxnFixtureMetadata) GetFnEntrypoint() string {
	if x != nil {
		return x.FnEntrypoint
	}
	return ""
}

type TxnFeeRateGovernor struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	TargetLamportsPerSignature uint64                 `protobuf:"varint,1,opt,name=target_lamports_per_signature,json=targetLamportsPerSignature,proto3" json:"target_lamports_per_signature,omitempty"`
	TargetSignaturesPerSlot    uint64                 `protobuf:"varint,2,opt,name=target_signatures_per_slot,json=targetSignaturesPerSlot,proto3" json:"target_signatures_per_slot,omitempty"`
	MinLamportsPerSignature    uint64                 `protobuf:"varint,3,opt,name=min_lamports_per_signature,json=minLamportsPerSignature,proto3" json:"min_lamports_per_signature,omitempty"`
	MaxLamportsPerSignature    uint64                 `protobuf:"varint,4,opt,name=max_lamports_per_signature,json=maxLamportsPerSignature,proto3" json:"max_lamports_per_signature,omitempty"`
	BurnPercent                uint32                 `protobuf:"varint,5,opt,name=burn_percent,json=burnPercent,proto3" json:"burn_percent,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *TxnFeeRateGovernor) Reset() {
	*x = TxnFeeRateGovernor{}
	mi := &file_txn_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnFeeRateGovernor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnFeeRateGovernor) ProtoMessage() {}

func (x *TxnFeeRateGovernor) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnFeeRateGovernor.ProtoReflect.Descriptor instead.
func (*TxnFeeRateGovernor) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{3}
}

func (x *TxnFeeRateGovernor) GetTargetLamportsPerSignature() uint64 {
	if x != nil {
		return x.TargetLamportsPerSignature
	}
	return 0
}

func (x *TxnFeeRateGovernor) GetTargetSignaturesPerSlot() uint64 {
	if x != nil {
		return x.TargetSignaturesPerSlot
	}
	return 0
}

func (x *TxnFeeRateGovernor) GetMinLamportsPerSignature() uint64 {
	if x != nil {
		return x.MinLamportsPerSignature
	}
	return 0
}

func (x *TxnFeeRateGovernor) GetMaxLamportsPerSignature() uint64 {
	if x != nil {
		return x.MaxLamportsPerSignature
	}
	return 0
}

func (x *TxnFeeRateGovernor) GetBurnPercent() uint32 {
	if x != nil {
		return x.BurnPercent
	}
	return 0
}

type TxnEpochSchedule struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SlotsPerEpoch            uint64                 `protobuf:"varint,1,opt,name=slots_per_epoch,json=slotsPerEpoch,proto3" json:"slots_per_epoch,omitempty"`
	LeaderScheduleSlotOffset uint64                 `protobuf:"varint,2,opt,name=leader_schedule_slot_offset,json=leaderScheduleSlotOffset,proto3" json:"leader_schedule_slot_offset,omitempty"`
	Warmup                   bool                   `protobuf:"varint,3,opt,name=warmup,proto3" json:"warmup,omitempty"`
	FirstNormalEpoch         uint64                 `protobuf:"varint,4,opt,name=first_normal_epoch,json=firstNormalEpoch,proto3" json:"first_normal_epoch,omitempty"`
	FirstNormalSlot          uint64                 `protobuf:"varint,5,opt,name=first_normal_slot,json=firstNormalSlot,proto3" json:"first_normal_slot,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TxnEpochSchedule) Reset() {
	*x = TxnEpochSchedule{}
	mi := &file_txn_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnEpochSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnEpochSchedule) ProtoMessage() {}

func (x *TxnEpochSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnEpochSchedule.ProtoReflect.Descriptor instead.
func (*TxnEpochSchedule) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{4}
}

func (x *TxnEpochSchedule) GetSlotsPerEpoch() uint64 {
	if x != nil {
		return x.SlotsPerEpoch
	}
	return 0
}

func (x *TxnEpochSchedule) GetLeaderScheduleSlotOffset() uint64 {
	if x != nil {
		return x.LeaderScheduleSlotOffset
	}
	return 0
}

func (x *TxnEpochSchedule) GetWarmup() bool {
	if x != nil {
		return x.Warmup
	}
	return false
}

func (x *TxnEpochSchedule) GetFirstNormalEpoch() uint64 {
	if x != nil {
		return x.FirstNormalEpoch
	}
	return 0
}

func (x *TxnEpochSchedule) GetFirstNormalSlot() uint64 {
	if x != nil {
		return x.FirstNormalSlot
	}
	return 0
}

type TxnRent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LamportsPerByteYear uint64                 `protobuf:"varint,1,opt,name=lamports_per_byte_year,json=lamportsPerByteYear,proto3" json:"lamports_per_byte_year,omitempty"`
	ExemptionThreshold  float64                `protobuf:"fixed64,2,opt,name=exemption_threshold,json=exemptionThreshold,proto3" json:"exemption_threshold,omitempty"`
	BurnPercent         uint32                 `protobuf:"varint,3,opt,name=burn_percent,json=burnPercent,proto3" json:"burn_percent,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TxnRent) Reset() {
	*x = TxnRent{}
	mi := &file_txn_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnRent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnRent) ProtoMessage() {}

func (x *TxnRent) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnRent.ProtoReflect.Descriptor instead.
func (*TxnRent) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{5}
}

func (x *TxnRent) GetLamportsPerByteYear() uint64 {
	if x != nil {
		return x.LamportsPerByteYear
	}
	return 0
}

func (x *TxnRent) GetExemptionThreshold() float64 {
	if x != nil {
		return x.ExemptionThreshold
	}
	return 0
}

func (x *TxnRent) GetBurnPercent() uint32 {
	if x != nil {
		return x.BurnPercent
	}
	return 0
}

type TxnBlockhashQueueEntry struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Blockhash            []byte                 `protobuf:"bytes,1,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	LamportsPerSignature uint64                 `protobuf:"varint,2,opt,name=lamports_per_signature,json=lamportsPerSignature,proto3" json:"lamports_per_signature,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TxnBlockhashQueueEntry) Reset() {
	*x = TxnBlockhashQueueEntry{}
	mi := &file_txn_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnBlockhashQueueEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnBlockhashQueueEntry) ProtoMessage() {}

func (x *TxnBlockhashQueueEntry) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnBlockhashQueueEntry.ProtoReflect.Descriptor instead.
func (*TxnBlockhashQueueEntry) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{6}
}

func (x *TxnBlockhashQueueEntry) GetBlockhash() []byte {
	if x != nil {
		return x.Blockhash
	}
	return nil
}

func (x *TxnBlockhashQueueEntry) GetLamportsPerSignature() uint64 {
	if x != nil {
		return x.LamportsPerSignature
	}
	return 0
}

type TxnMessageHeader struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	NumRequiredSignatures       uint32                 `protobuf:"varint,1,opt,name=num_required_signatures,json=numRequiredSignatures,proto3" json:"num_required_signatures,omitempty"`
	NumReadonlySignedAccounts   uint32                 `protobuf:"varint,2,opt,name=num_readonly_signed_accounts,json=numReadonlySignedAccounts,proto3" json:"num_readonly_signed_accounts,omitempty"`
	NumReadonlyUnsignedAccounts uint32                 `protobuf:"varint,3,opt,name=num_readonly_unsigned_accounts,json=numReadonlyUnsignedAccounts,proto3" json:"num_readonly_unsigned_accounts,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *TxnMessageHeader) Reset() {
	*x = TxnMessageHeader{}
	mi := &file_txn_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnMessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnMessageHeader) ProtoMessage() {}

func (x *TxnMessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnMessageHeader.ProtoReflect.Descriptor instead.
func (*TxnMessageHeader) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{7}
}

func (x *TxnMessageHeader) GetNumRequiredSignatures() uint32 {
	if x != nil {
		return x.NumRequiredSignatures
	}
	return 0
}

func (x *TxnMessageHeader) GetNumReadonlySignedAccounts() uint32 {
	if x != nil {
		return x.NumReadonlySignedAccounts
	}
	return 0
}

func (x *TxnMessageHeader) GetNumReadonlyUnsignedAccounts() uint32 {
	if x != nil {
		return x.NumReadonlyUnsignedAccounts
	}
	return 0
}

type TxnCompiledInstruction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProgramIdIndex uint32                 `protobuf:"varint,1,opt,name=program_id_index,json=programIdIndex,proto3" json:"program_id_index,omitempty"`
	Accounts       []uint32               `protobuf:"varint,2,rep,packed,name=accounts,proto3" json:"accounts,omitempty"`
	Data           []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TxnCompiledInstruction) Reset() {
	*x = TxnCompiledInstruction{}
	mi := &file_txn_v2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnCompiledInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnCompiledInstruction) ProtoMessage() {}

func (x *TxnCompiledInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnCompiledInstruction.ProtoReflect.Descriptor instead.
func (*TxnCompiledInstruction) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{8}
}

func (x *TxnCompiledInstruction) GetProgramIdIndex() uint32 {
	if x != nil {
		return x.ProgramIdIndex
	}
	return 0
}

func (x *TxnCompiledInstruction) GetAccounts() []uint32 {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *TxnCompiledInstruction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TxnMessageAddressTableLookup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountKey      []byte                 `protobuf:"bytes,1,opt,name=account_key,json=accountKey,proto3" json:"account_key,omitempty"`
	WritableIndexes []uint32               `protobuf:"varint,2,rep,packed,name=writable_indexes,json=writableIndexes,proto3" json:"writable_indexes,omitempty"`
	ReadonlyIndexes []uint32               `protobuf:"varint,3,rep,packed,name=readonly_indexes,json=readonlyIndexes,proto3" json:"readonly_indexes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TxnMessageAddressTableLookup) Reset() {
	*x = TxnMessageAddressTableLookup{}
	mi := &file_txn_v2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnMessageAddressTableLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnMessageAddressTableLookup) ProtoMessage() {}

func (x *TxnMessageAddressTableLookup) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnMessageAddressTableLookup.ProtoReflect.Descriptor instead.
func (*TxnMessageAddressTableLookup) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{9}
}

func (x *TxnMessageAddressTableLookup) GetAccountKey() []byte {
	if x != nil {
		return x.AccountKey
	}
	return nil
}

func (x *TxnMessageAddressTableLookup) GetWritableIndexes() []uint32 {
	if x != nil {
		return x.WritableIndexes
	}
	return nil
}

func (x *TxnMessageAddressTableLookup) GetReadonlyIndexes() []uint32 {
	if x != nil {
		return x.ReadonlyIndexes
	}
	return nil
}

type TxnTransactionMessage struct {
	state               protoimpl.MessageState          `protogen:"open.v1"`
	IsLegacy            bool                            `protobuf:"varint,1,opt,name=is_legacy,json=isLegacy,proto3" json:"is_legacy,omitempty"`
	Header              *TxnMessageHeader               `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	AccountKeys         [][]byte                        `protobuf:"bytes,3,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"`
	RecentBlockhash     []byte                          `protobuf:"bytes,5,opt,name=recent_blockhash,json=recentBlockhash,proto3" json:"recent_blockhash,omitempty"`
	Instructions        []*TxnCompiledInstruction       `protobuf:"bytes,6,rep,name=instructions,proto3" json:"instructions,omitempty"`
	AddressTableLookups []*TxnMessageAddressTableLookup `protobuf:"bytes,7,rep,name=address_table_lookups,json=addressTableLookups,proto3" json:"address_table_lookups,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TxnTransactionMessage) Reset() {
	*x = TxnTransactionMessage{}
	mi := &file_txn_v2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnTransactionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnTransactionMessage) ProtoMessage() {}

func (x *TxnTransactionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnTransactionMessage.ProtoReflect.Descriptor instead.
func (*TxnTransactionMessage) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{10}
}

func (x *TxnTransactionMessage) GetIsLegacy() bool {
	if x != nil {
		return x.IsLegacy
	}
	return false
}

func (x *TxnTransactionMessage) GetHeader() *TxnMessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TxnTransactionMessage) GetAccountKeys() [][]byte {
	if x != nil {
		return x.AccountKeys
	}
	return nil
}

func (x *TxnTransactionMessage) GetRecentBlockhash() []byte {
	if x != nil {
		return x.RecentBlockhash
	}
	return nil
}

func (x *TxnTransactionMessage) GetInstructions() []*TxnCompiledInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *TxnTransactionMessage) GetAddressTableLookups() []*TxnMessageAddressTableLookup {
	if x != nil {
		return x.AddressTableLookups
	}
	return nil
}

type TxnSanitizedTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *TxnTransactionMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MessageHash   []byte                 `protobuf:"bytes,2,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	Signatures    [][]byte               `protobuf:"bytes,4,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnSanitizedTransaction) Reset() {
	*x = TxnSanitizedTransaction{}
	mi := &file_txn_v2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnSanitizedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnSanitizedTransaction) ProtoMessage() {}

func (x *TxnSanitizedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnSanitizedTransaction.ProtoReflect.Descriptor instead.
func (*TxnSanitizedTransaction) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{11}
}

func (x *TxnSanitizedTransaction) GetMessage() *TxnTransactionMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TxnSanitizedTransaction) GetMessageHash() []byte {
	if x != nil {
		return x.MessageHash
	}
	return nil
}

func (x *TxnSanitizedTransaction) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type TxnBankV2 struct {
	state                   protoimpl.MessageState    `protogen:"open.v1"`
	BlockhashQueue          []*TxnBlockhashQueueEntry `protobuf:"bytes,1,rep,name=blockhash_queue,json=blockhashQueue,proto3" json:"blockhash_queue,omitempty"`
	RbhLamportsPerSignature uint32                    `protobuf:"varint,2,opt,name=rbh_lamports_per_signature,json=rbhLamportsPerSignature,proto3" json:"rbh_lamports_per_signature,omitempty"`
	FeeRateGovernor         *TxnFeeRateGovernor       `protobuf:"bytes,3,opt,name=fee_rate_governor,json=feeRateGovernor,proto3" json:"fee_rate_governor,omitempty"`
	TotalEpochStake         uint64                    `protobuf:"varint,4,opt,name=total_epoch_stake,json=totalEpochStake,proto3" json:"total_epoch_stake,omitempty"`
	EpochSchedule           *TxnEpochSchedule         `protobuf:"bytes,5,opt,name=epoch_schedule,json=epochSchedule,proto3" json:"epoch_schedule,omitempty"`
	Rent                    *TxnRent                  `protobuf:"bytes,6,opt,name=rent,proto3" json:"rent,omitempty"`
	Features                *TxnFeatureSet            `protobuf:"bytes,7,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TxnBankV2) Reset() {
	*x = TxnBankV2{}
	mi := &file_txn_v2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnBankV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnBankV2) ProtoMessage() {}

func (x *TxnBankV2) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnBankV2.ProtoReflect.Descriptor instead.
func (*TxnBankV2) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{12}
}

func (x *TxnBankV2) GetBlockhashQueue() []*TxnBlockhashQueueEntry {
	if x != nil {
		return x.BlockhashQueue
	}
	return nil
}

func (x *TxnBankV2) GetRbhLamportsPerSignature() uint32 {
	if x != nil {
		return x.RbhLamportsPerSignature
	}
	return 0
}

func (x *TxnBankV2) GetFeeRateGovernor() *TxnFeeRateGovernor {
	if x != nil {
		return x.FeeRateGovernor
	}
	return nil
}

func (x *TxnBankV2) GetTotalEpochStake() uint64 {
	if x != nil {
		return x.TotalEpochStake
	}
	return 0
}

func (x *TxnBankV2) GetEpochSchedule() *TxnEpochSchedule {
	if x != nil {
		return x.EpochSchedule
	}
	return nil
}

func (x *TxnBankV2) GetRent() *TxnRent {
	if x != nil {
		return x.Rent
	}
	return nil
}

func (x *TxnBankV2) GetFeatures() *TxnFeatureSet {
	if x != nil {
		return x.Features
	}
	return nil
}

type TxnContextV2 struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	Tx                *TxnSanitizedTransaction `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	AccountSharedData []*TxnAcctState          `protobuf:"bytes,2,rep,name=account_shared_data,json=accountSharedData,proto3" json:"account_shared_data,omitempty"`
	Bank              *TxnBankV2               `protobuf:"bytes,6,opt,name=bank,proto3" json:"bank,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TxnContextV2) Reset() {
	*x = TxnContextV2{}
	mi := &file_txn_v2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnContextV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnContextV2) ProtoMessage() {}

func (x *TxnContextV2) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnContextV2.ProtoReflect.Descriptor instead.
func (*TxnContextV2) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{13}
}

func (x *TxnContextV2) GetTx() *TxnSanitizedTransaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *TxnContextV2) GetAccountSharedData() []*TxnAcctState {
	if x != nil {
		return x.AccountSharedData
	}
	return nil
}

func (x *TxnContextV2) GetBank() *TxnBankV2 {
	if x != nil {
		return x.Bank
	}
	return nil
}

type TxnFeeDetailsV2 struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionFee    uint64                 `protobuf:"varint,1,opt,name=transaction_fee,json=transactionFee,proto3" json:"transaction_fee,omitempty"`
	PrioritizationFee uint64                 `protobuf:"varint,2,opt,name=prioritization_fee,json=prioritizationFee,proto3" json:"prioritization_fee,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TxnFeeDetailsV2) Reset() {
	*x = TxnFeeDetailsV2{}
	mi := &file_txn_v2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnFeeDetailsV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnFeeDetailsV2) ProtoMessage() {}

func (x *TxnFeeDetailsV2) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnFeeDetailsV2.ProtoReflect.Descriptor instead.
func (*TxnFeeDetailsV2) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{14}
}

func (x *TxnFeeDetailsV2) GetTransactionFee() uint64 {
	if x != nil {
		return x.TransactionFee
	}
	return 0
}

func (x *TxnFeeDetailsV2) GetPrioritizationFee() uint64 {
	if x != nil {
		return x.PrioritizationFee
	}
	return 0
}

type TxnResultV2 struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Executed               bool                   `protobuf:"varint,1,opt,name=executed,proto3" json:"executed,omitempty"`
	SanitizationError      bool                   `protobuf:"varint,2,opt,name=sanitization_error,json=sanitizationError,proto3" json:"sanitization_error,omitempty"`
	IsOk                   bool                   `protobuf:"varint,5,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	Status                 uint32                 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	InstructionError       uint32                 `protobuf:"varint,7,opt,name=instruction_error,json=instructionError,proto3" json:"instruction_error,omitempty"`
	InstructionErrorIndex  uint32                 `protobuf:"varint,8,opt,name=instruction_error_index,json=instructionErrorIndex,proto3" json:"instruction_error_index,omitempty"`
	CustomError            uint32                 `protobuf:"varint,9,opt,name=custom_error,json=customError,proto3" json:"custom_error,omitempty"`
	ReturnData             []byte                 `protobuf:"bytes,10,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	ExecutedUnits          uint64                 `protobuf:"varint,11,opt,name=executed_units,json=executedUnits,proto3" json:"executed_units,omitempty"`
	FeeDetails             *TxnFeeDetailsV2       `protobuf:"bytes,12,opt,name=fee_details,json=feeDetails,proto3" json:"fee_details,omitempty"`
	LoadedAccountsDataSize uint64                 `protobuf:"varint,13,opt,name=loaded_accounts_data_size,json=loadedAccountsDataSize,proto3" json:"loaded_accounts_data_size,omitempty"`
	ModifiedAccounts       []*TxnAcctState        `protobuf:"bytes,14,rep,name=modified_accounts,json=modifiedAccounts,proto3" json:"modified_accounts,omitempty"`
	RollbackAccounts       []*TxnAcctState        `protobuf:"bytes,15,rep,name=rollback_accounts,json=rollbackAccounts,proto3" json:"rollback_accounts,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TxnResultV2) Reset() {
	*x = TxnResultV2{}
	mi := &file_txn_v2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnResultV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnResultV2) ProtoMessage() {}

func (x *TxnResultV2) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnResultV2.ProtoReflect.Descriptor instead.
func (*TxnResultV2) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{15}
}

func (x *TxnResultV2) GetExecuted() bool {
	if x != nil {
		return x.Executed
	}
	return false
}

func (x *TxnResultV2) GetSanitizationError() bool {
	if x != nil {
		return x.SanitizationError
	}
	return false
}

func (x *TxnResultV2) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *TxnResultV2) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TxnResultV2) GetInstructionError() uint32 {
	if x != nil {
		return x.InstructionError
	}
	return 0
}

func (x *TxnResultV2) GetInstructionErrorIndex() uint32 {
	if x != nil {
		return x.InstructionErrorIndex
	}
	return 0
}

func (x *TxnResultV2) GetCustomError() uint32 {
	if x != nil {
		return x.CustomError
	}
	return 0
}

func (x *TxnResultV2) GetReturnData() []byte {
	if x != nil {
		return x.ReturnData
	}
	return nil
}

func (x *TxnResultV2) GetExecutedUnits() uint64 {
	if x != nil {
		return x.ExecutedUnits
	}
	return 0
}

func (x *TxnResultV2) GetFeeDetails() *TxnFeeDetailsV2 {
	if x != nil {
		return x.FeeDetails
	}
	return nil
}

func (x *TxnResultV2) GetLoadedAccountsDataSize() uint64 {
	if x != nil {
		return x.LoadedAccountsDataSize
	}
	return 0
}

func (x *TxnResultV2) GetModifiedAccounts() []*TxnAcctState {
	if x != nil {
		return x.ModifiedAccounts
	}
	return nil
}

func (x *TxnResultV2) GetRollbackAccounts() []*TxnAcctState {
	if x != nil {
		return x.RollbackAccounts
	}
	return nil
}

type TxnFixtureV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *TxnFixtureMetadata    `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Input         *TxnContextV2          `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        *TxnResultV2           `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnFixtureV2) Reset() {
	*x = TxnFixtureV2{}
	mi := &file_txn_v2_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnFixtureV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnFixtureV2) ProtoMessage() {}

func (x *TxnFixtureV2) ProtoReflect() protoreflect.Message {
	mi := &file_txn_v2_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnFixtureV2.ProtoReflect.Descriptor instead.
func (*TxnFixtureV2) Descriptor() ([]byte, []int) {
	return file_txn_v2_proto_rawDescGZIP(), []int{16}
}

func (x *TxnFixtureV2) GetMetadata() *TxnFixtureMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TxnFixtureV2) GetInput() *TxnContextV2 {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TxnFixtureV2) GetOutput() *TxnResultV2 {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_txn_v2_proto protoreflect.FileDescriptor

const file_txn_v2_proto_rawDesc = "" +
	"\n" +
	"\ftxn_v2.proto\x12\x16org.solana.sealevel.v2\"+\n" +
	"\rTxnFeatureSet\x12\x1a\n" +
	"\bfeatures\x18\x01 \x03(\x06R\bfeatures\"\x9a\x01\n" +
	"\fTxnAcctState\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x1a\n" +
	"\blamports\x18\x02 \x01(\x04R\blamports\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"executable\x18\x04 \x01(\bR\n" +
	"executable\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\fR\x05ownerJ\x04\b\x05\x10\x06J\x04\b\a\x10\b\"9\n" +
	"\x12TxnFixtureMetadata\x12#\n" +
	"\rfn_entrypoint\x18\x01 \x01(\tR\ffnEntrypoint\"\xb1\x02\n" +
	"\x12TxnFeeRateGovernor\x12A\n" +
	"\x1dtarget_lamports_per_signature\x18\x01 \x01(\x04R\x1atargetLamportsPerSignature\x12;\n" +
	"\x1atarget_signatures_per_slot\x18\x02 \x01(\x04R\x17targetSignaturesPerSlot\x12;\n" +
	"\x1amin_lamports_per_signature\x18\x03 \x01(\x04R\x17minLamportsPerSignature\x12;\n" +
	"\x1amax_lamports_per_signature\x18\x04 \x01(\x04R\x17maxLamportsPerSignature\x12!\n" +
	"\fburn_percent\x18\x05 \x01(\rR\vburnPercent\"\xeb\x01\n" +
	"\x10TxnEpochSchedule\x12&\n" +
	"\x0fslots_per_epoch\x18\x01 \x01(\x04R\rslotsPerEpoch\x12=\n" +
	"\x1bleader_schedule_slot_offset\x18\x02 \x01(\x04R\x18leaderScheduleSlotOffset\x12\x16\n" +
	"\x06warmup\x18\x03 \x01(\bR\x06warmup\x12,\n" +
	"\x12first_normal_epoch\x18\x04 \x01(\x04R\x10firstNormalEpoch\x12*\n" +
	"\x11first_normal_slot\x18\x05 \x01(\x04R\x0ffirstNormalSlot\"\x92\x01\n" +
	"\aTxnRent\x123\n" +
	"\x16lamports_per_byte_year\x18\x01 \x01(\x04R\x13lamportsPerByteYear\x12/\n" +
	"\x13exemption_threshold\x18\x02 \x01(\x01R\x12exemptionThreshold\x12!\n" +
	"\fburn_percent\x18\x03 \x01(\rR\vburnPercent\"l\n" +
	"\x16TxnBlockhashQueueEntry\x12\x1c\n" +
	"\tblockhash\x18\x01 \x01(\fR\tblockhash\x124\n" +
	"\x16lamports_per_signature\x18\x02 \x01(\x04R\x14lamportsPerSignature\"\xd0\x01\n" +
	"\x10TxnMessageHeader\x126\n" +
	"\x17num_required_signatures\x18\x01 \x01(\rR\x15numRequiredSignatures\x12?\n" +
	"\x1cnum_readonly_signed_accounts\x18\x02 \x01(\rR\x19numReadonlySignedAccounts\x12C\n" +
	"\x1enum_readonly_unsigned_accounts\x18\x03 \x01(\rR\x1bnumReadonlyUnsignedAccounts\"r\n" +
	"\x16TxnCompiledInstruction\x12(\n" +
	"\x10program_id_index\x18\x01 \x01(\rR\x0eprogramIdIndex\x12\x1a\n" +
	"\baccounts\x18\x02 \x03(\rR\baccounts\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x95\x01\n" +
	"\x1cTxnMessageAddressTableLookup\x12\x1f\n" +
	"\vaccount_key\x18\x01 \x01(\fR\n" +
	"accountKey\x12)\n" +
	"\x10writable_indexes\x18\x02 \x03(\rR\x0fwritableIndexes\x12)\n" +
	"\x10readonly_indexes\x18\x03 \x03(\rR\x0freadonlyIndexes\"\x82\x03\n" +
	"\x15TxnTransactionMessage\x12\x1b\n" +
	"\tis_legacy\x18\x01 \x01(\bR\bisLegacy\x12@\n" +
	"\x06header\x18\x02 \x01(\v2(.org.solana.sealevel.v2.TxnMessageHeaderR\x06header\x12!\n" +
	"\faccount_keys\x18\x03 \x03(\fR\vaccountKeys\x12)\n" +
	"\x10recent_blockhash\x18\x05 \x01(\fR\x0frecentBlockhash\x12R\n" +
	"\finstructions\x18\x06 \x03(\v2..org.solana.sealevel.v2.TxnCompiledInstructionR\finstructions\x12h\n" +
	"\x15address_table_lookups\x18\a \x03(\v24.org.solana.sealevel.v2.TxnMessageAddressTableLookupR\x13addressTableLookups\"\xa5\x01\n" +
	"\x17TxnSanitizedTransaction\x12G\n" +
	"\amessage\x18\x01 \x01(\v2-.org.solana.sealevel.v2.TxnTransactionMessageR\amessage\x12!\n" +
	"\fmessage_hash\x18\x02 \x01(\fR\vmessageHash\x12\x1e\n" +
	"\n" +
	"signatures\x18\x04 \x03(\fR\n" +
	"signatures\"\xf4\x03\n" +
	"\tTxnBankV2\x12W\n" +
	"\x0fblockhash_queue\x18\x01 \x03(\v2..org.solana.sealevel.v2.TxnBlockhashQueueEntryR\x0eblockhashQueue\x12;\n" +
	"\x1arbh_lamports_per_signature\x18\x02 \x01(\rR\x17rbhLamportsPerSignature\x12V\n" +
	"\x11fee_rate_governor\x18\x03 \x01(\v2*.org.solana.sealevel.v2.TxnFeeRateGovernorR\x0ffeeRateGovernor\x12*\n" +
	"\x11total_epoch_stake\x18\x04 \x01(\x04R\x0ftotalEpochStake\x12O\n" +
	"\x0eepoch_schedule\x18\x05 \x01(\v2(.org.solana.sealevel.v2.TxnEpochScheduleR\repochSchedule\x123\n" +
	"\x04rent\x18\x06 \x01(\v2\x1f.org.solana.sealevel.v2.TxnRentR\x04rent\x12A\n" +
	"\bfeatures\x18\a \x01(\v2%.org.solana.sealevel.v2.TxnFeatureSetR\bfeaturesJ\x04\b\b\x10\t\"\xee\x01\n" +
	"\fTxnContextV2\x12?\n" +
	"\x02tx\x18\x01 \x01(\v2/.org.solana.sealevel.v2.TxnSanitizedTransactionR\x02tx\x12T\n" +
	"\x13account_shared_data\x18\x02 \x03(\v2$.org.solana.sealevel.v2.TxnAcctStateR\x11accountSharedData\x125\n" +
	"\x04bank\x18\x06 \x01(\v2!.org.solana.sealevel.v2.TxnBankV2R\x04bankJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06\"i\n" +
	"\x0fTxnFeeDetailsV2\x12'\n" +
	"\x0ftransaction_fee\x18\x01 \x01(\x04R\x0etransactionFee\x12-\n" +
	"\x12prioritization_fee\x18\x02 \x01(\x04R\x11prioritizationFee\"\x8c\x05\n" +
	"\vTxnResultV2\x12\x1a\n" +
	"\bexecuted\x18\x01 \x01(\bR\bexecuted\x12-\n" +
	"\x12sanitization_error\x18\x02 \x01(\bR\x11sanitizationError\x12\x13\n" +
	"\x05is_ok\x18\x05 \x01(\bR\x04isOk\x12\x16\n" +
	"\x06status\x18\x06 \x01(\rR\x06status\x12+\n" +
	"\x11instruction_error\x18\a \x01(\rR\x10instructionError\x126\n" +
	"\x17instruction_error_index\x18\b \x01(\rR\x15instructionErrorIndex\x12!\n" +
	"\fcustom_error\x18\t \x01(\rR\vcustomError\x12\x1f\n" +
	"\vreturn_data\x18\n" +
	" \x01(\fR\n" +
	"returnData\x12%\n" +
	"\x0eexecuted_units\x18\v \x01(\x04R\rexecutedUnits\x12H\n" +
	"\vfee_details\x18\f \x01(\v2'.org.solana.sealevel.v2.TxnFeeDetailsV2R\n" +
	"feeDetails\x129\n" +
	"\x19loaded_accounts_data_size\x18\r \x01(\x04R\x16loadedAccountsDataSize\x12Q\n" +
	"\x11modified_accounts\x18\x0e \x03(\v2$.org.solana.sealevel.v2.TxnAcctStateR\x10modifiedAccounts\x12Q\n" +
	"\x11rollback_accounts\x18\x0f \x03(\v2$.org.solana.sealevel.v2.TxnAcctStateR\x10rollbackAccountsJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"\xcf\x01\n" +
	"\fTxnFixtureV2\x12F\n" +
	"\bmetadata\x18\x01 \x01(\v2*.org.solana.sealevel.v2.TxnFixtureMetadataR\bmetadata\x12:\n" +
	"\x05input\x18\x02 \x01(\v2$.org.solana.sealevel.v2.TxnContextV2R\x05input\x12;\n" +
	"\x06output\x18\x03 \x01(\v2#.org.solana.sealevel.v2.TxnResultV2R\x06outputB4Z2github.com/Overclock-Validator/mithril/conformanceb\x06proto3"

var (
	file_txn_v2_proto_rawDescOnce sync.Once
	file_txn_v2_proto_rawDescData []byte
)

func file_txn_v2_proto_rawDescGZIP() []byte {
	file_txn_v2_proto_rawDescOnce.Do(func() {
		file_txn_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txn_v2_proto_rawDesc), len(file_txn_v2_proto_rawDesc)))
	})
	return file_txn_v2_proto_rawDescData
}

var file_txn_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_txn_v2_proto_goTypes = []any{
	(*TxnFeatureSet)(nil),                // 0: org.solana.sealevel.v2.TxnFeatureSet
	(*TxnAcctState)(nil),                 // 1: org.solana.sealevel.v2.TxnAcctState
	(*TxnFixtureMetadata)(nil),           // 2: org.solana.sealevel.v2.TxnFixtureMetadata
	(*TxnFeeRateGovernor)(nil),           // 3: org.solana.sealevel.v2.TxnFeeRateGovernor
	(*TxnEpochSchedule)(nil),             // 4: org.solana.sealevel.v2.TxnEpochSchedule
	(*TxnRent)(nil),                      // 5: org.solana.sealevel.v2.TxnRent
	(*TxnBlockhashQueueEntry)(nil),       // 6: org.solana.sealevel.v2.TxnBlockhashQueueEntry
	(*TxnMessageHeader)(nil),             // 7: org.solana.sealevel.v2.TxnMessageHeader
	(*TxnCompiledInstruction)(nil),       // 8: org.solana.sealevel.v2.TxnCompiledInstruction
	(*TxnMessageAddressTableLookup)(nil), // 9: org.solana.sealevel.v2.TxnMessageAddressTableLookup
	(*TxnTransactionMessage)(nil),        // 10: org.solana.sealevel.v2.TxnTransactionMessage
	(*TxnSanitizedTransaction)(nil),      // 11: org.solana.sealevel.v2.TxnSanitizedTransaction
	(*TxnBankV2)(nil),                    // 12: org.solana.sealevel.v2.TxnBankV2
	(*TxnContextV2)(nil),                 // 13: org.solana.sealevel.v2.TxnContextV2
	(*TxnFeeDetailsV2)(nil),              // 14: org.solana.sealevel.v2.TxnFeeDetailsV2
	(*TxnResultV2)(nil),                  // 15: org.solana.sealevel.v2.TxnResultV2
	(*TxnFixtureV2)(nil),                 // 16: org.solana.sealevel.v2.TxnFixtureV2
}
var file_txn_v2_proto_depIdxs = []int32{
	7,  // 0: org.solana.sealevel.v2.TxnTransactionMessage.header:type_name -> org.solana.sealevel.v2.TxnMessageHeader
	8,  // 1: org.solana.sealevel.v2.TxnTransactionMessage.instructions:type_name -> org.solana.sealevel.v2.TxnCompiledInstruction
	9,  // 2: org.solana.sealevel.v2.TxnTransactionMessage.address_table_lookups:type_name -> org.solana.sealevel.v2.TxnMessageAddressTableLookup
	10, // 3: org.solana.sealevel.v2.TxnSanitizedTransaction.message:type_name -> org.solana.sealevel.v2.TxnTransactionMessage
	6,  // 4: org.solana.sealevel.v2.TxnBankV2.blockhash_queue:type_name -> org.solana.sealevel.v2.TxnBlockhashQueueEntry
	3,  // 5: org.solana.sealevel.v2.TxnBankV2.fee_rate_governor:type_name -> org.solana.sealevel.v2.TxnFeeRateGovernor
	4,  // 6: org.solana.sealevel.v2.TxnBankV2.epoch_schedule:type_name -> org.solana.sealevel.v2.TxnEpochSchedule
	5,  // 7: org.solana.sealevel.v2.TxnBankV2.rent:type_name -> org.solana.sealevel.v2.TxnRent
	0,  // 8: org.solana.sealevel.v2.TxnBankV2.features:type_name -> org.solana.sealevel.v2.TxnFeatureSet
	11, // 9: org.solana.sealevel.v2.TxnContextV2.tx:type_name -> org.solana.sealevel.v2.TxnSanitizedTransaction
	1,  // 10: org.solana.sealevel.v2.TxnContextV2.account_shared_data:type_name -> org.solana.sealevel.v2.TxnAcctState
	12, // 11: org.solana.sealevel.v2.TxnContextV2.bank:type_name -> org.solana.sealevel.v2.TxnBankV2
	14, // 12: org.solana.sealevel.v2.TxnResultV2.fee_details:type_name -> org.solana.sealevel.v2.TxnFeeDetailsV2
	1,  // 13: org.solana.sealevel.v2.TxnResultV2.modified_accounts:type_name -> org.solana.sealevel.v2.TxnAcctState
	1,  // 14: org.solana.sealevel.v2.TxnResultV2.rollback_accounts:type_name -> org.solana.sealevel.v2.TxnAcctState
	2,  // 15: org.solana.sealevel.v2.TxnFixtureV2.metadata:type_name -> org.solana.sealevel.v2.TxnFixtureMetadata
	13, // 16: org.solana.sealevel.v2.TxnFixtureV2.input:type_name -> org.solana.sealevel.v2.TxnContextV2
	15, // 17: org.solana.sealevel.v2.TxnFixtureV2.output:type_name -> org.solana.sealevel.v2.TxnResultV2
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_txn_v2_proto_init() }
func file_txn_v2_proto_init() {
	if File_txn_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txn_v2_proto_rawDesc), len(file_txn_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txn_v2_proto_goTypes,
		DependencyIndexes: file_txn_v2_proto_depIdxs,
		MessageInfos:      file_txn_v2_proto_msgTypes,
	}.Build()
	File_txn_v2_proto = out.File
	file_txn_v2_proto_goTypes = nil
	file_txn_v2_proto_depIdxs = nil
}
