// Minimal subset of Perfetto trace protos for converting Go traces.
// Based on https://perfetto.dev/docs/reference/trace-packet-proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: perfetto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackEvent_Type int32

const (
	TrackEvent_TYPE_UNSPECIFIED TrackEvent_Type = 0
	TrackEvent_TYPE_SLICE_BEGIN TrackEvent_Type = 1
	TrackEvent_TYPE_SLICE_END   TrackEvent_Type = 2
	TrackEvent_TYPE_INSTANT     TrackEvent_Type = 3
)

// Enum value maps for TrackEvent_Type.
var (
	TrackEvent_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_SLICE_BEGIN",
		2: "TYPE_SLICE_END",
		3: "TYPE_INSTANT",
	}
	TrackEvent_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_SLICE_BEGIN": 1,
		"TYPE_SLICE_END":   2,
		"TYPE_INSTANT":     3,
	}
)

func (x TrackEvent_Type) Enum() *TrackEvent_Type {
	p := new(TrackEvent_Type)
	*p = x
	return p
}

func (x TrackEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_perfetto_proto_enumTypes[0].Descriptor()
}

func (TrackEvent_Type) Type() protoreflect.EnumType {
	return &file_perfetto_proto_enumTypes[0]
}

func (x TrackEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackEvent_Type.Descriptor instead.
func (TrackEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_perfetto_proto_rawDescGZIP(), []int{5, 0}
}

// Top-level trace container
type Trace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packet        []*TracePacket         `protobuf:"bytes,1,rep,name=packet,proto3" json:"packet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_perfetto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_perfetto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_perfetto_proto_rawDescGZIP(), []int{0}
}

func (x *Trace) GetPacket() []*TracePacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

// A single trace packet
type TracePacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp in nanoseconds
	Timestamp uint64 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Sequence ID for ordering
	TrustedPacketSequenceId uint32 `protobuf:"varint,10,opt,name=trusted_packet_sequence_id,json=trustedPacketSequenceId,proto3" json:"trusted_packet_sequence_id,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*TracePacket_TrackDescriptor
	//	*TracePacket_TrackEvent
	Data          isTracePacket_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracePacket) Reset() {
	*x = TracePacket{}
	mi := &file_perfetto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracePacket) ProtoMessage() {}

func (x *TracePacket) ProtoReflect() protoreflect.Message {
	mi := &file_perfetto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracePacket.ProtoReflect.Descriptor instead.
func (*TracePacket) Descriptor() ([]byte, []int) {
	return file_perfetto_proto_rawDescGZIP(), []int{1}
}

func (x *TracePacket) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TracePacket) GetTrustedPacketSequenceId() uint32 {
	if x != nil {
		return x.TrustedPacketSequenceId
	}
	return 0
}

func (x *TracePacket) GetData() isTracePacket_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TracePacket) GetTrackDescriptor() *TrackDescriptor {
	if x != nil {
		if x, ok := x.Data.(*TracePacket_TrackDescriptor); ok {
			return x.TrackDescriptor
		}
	}
	return nil
}

func (x *TracePacket) GetTrackEvent() *TrackEvent {
	if x != nil {
		if x, ok := x.Data.(*TracePacket_TrackEvent); ok {
			return x.TrackEvent
		}
	}
	return nil
}

type isTracePacket_Data interface {
	isTracePacket_Data()
}

type TracePacket_TrackDescriptor struct {
	TrackDescriptor *TrackDescriptor `protobuf:"bytes,60,opt,name=track_descriptor,json=trackDescriptor,proto3,oneof"`
}

type TracePacket_TrackEvent struct {
	TrackEvent *TrackEvent `protobuf:"bytes,11,opt,name=track_event,json=trackEvent,proto3,oneof"`
}

func (*TracePacket_TrackDescriptor) isTracePacket_Data() {}

func (*TracePacket_TrackEvent) isTracePacket_Data() {}

// Describes a track (process, thread, or custom)
type TrackDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          uint64                 `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Process       *ProcessDescriptor     `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`
	Thread        *ThreadDescriptor      `protobuf:"bytes,4,opt,name=thread,proto3" json:"thread,omitempty"`
	ParentUuid    uint64                 `protobuf:"varint,5,opt,name=parent_uuid,json=parentUuid,proto3" json:"parent_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackDescriptor) Reset() {
	*x = TrackDescriptor{}
	mi := &file_perfetto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackDescriptor) ProtoMessage() {}

func (x *TrackDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_perfetto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackDescriptor.ProtoReflect.Descriptor instead.
func (*TrackDescriptor) Descriptor() ([]byte, []int) {
	return file_perfetto_proto_rawDescGZIP(), []int{2}
}

func (x *TrackDescriptor) GetUuid() uint64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *TrackDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrackDescriptor) GetProcess() *ProcessDescriptor {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *TrackDescriptor) GetThread() *ThreadDescriptor {
	if x != nil {
		return x.Thread
	}
	return nil
}

func (x *TrackDescriptor) GetParentUuid() uint64 {
	if x != nil {
		return x.ParentUuid
	}
	return 0
}

// Process descriptor
type ProcessDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	ProcessName   string                 `protobuf:"bytes,6,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDescriptor) Reset() {
	*x = ProcessDescriptor{}
	mi := &file_perfetto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDescriptor) ProtoMessage() {}

func (x *ProcessDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_perfetto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDescriptor.ProtoReflect.Descriptor instead.
func (*ProcessDescriptor) Descriptor() ([]byte, []int) {
	return file_perfetto_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessDescriptor) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessDescriptor) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

// Thread descriptor
type ThreadDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Tid           int32                  `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
	ThreadName    string                 `protobuf:"bytes,5,opt,name=thread_name,json=threadName,proto3" json:"thread_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadDescriptor) Reset() {
	*x = ThreadDescriptor{}
	mi := &file_perfetto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadDescriptor) ProtoMessage() {}

func (x *ThreadDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_perfetto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadDescriptor.ProtoReflect.Descriptor instead.
func (*ThreadDescriptor) Descriptor() ([]byte, []int) {
	return file_perfetto_proto_rawDescGZIP(), []int{4}
}

func (x *ThreadDescriptor) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ThreadDescriptor) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *ThreadDescriptor) GetThreadName() string {
	if x != nil {
		return x.ThreadName
	}
	return ""
}

// A trace event on a track
type TrackEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Categories for filtering
	Categories []string `protobuf:"bytes,22,rep,name=categories,proto3" json:"categories,omitempty"`
	// Event name
	Name string `protobuf:"bytes,23,opt,name=name,proto3" json:"name,omitempty"`
	// Event type
	Type TrackEvent_Type `protobuf:"varint,9,opt,name=type,proto3,enum=perfetto.protos.TrackEvent_Type" json:"type,omitempty"`
	// Track this event belongs to
	TrackUuid uint64 `protobuf:"varint,11,opt,name=track_uuid,json=trackUuid,proto3" json:"track_uuid,omitempty"`
	// Debug annotations (key-value metadata)
	DebugAnnotations []*DebugAnnotation `protobuf:"bytes,4,rep,name=debug_annotations,json=debugAnnotations,proto3" json:"debug_annotations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrackEvent) Reset() {
	*x = TrackEvent{}
	mi := &file_perfetto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEvent) ProtoMessage() {}

func (x *TrackEvent) ProtoReflect() protoreflect.Message {
	mi := &file_perfetto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEvent.ProtoReflect.Descriptor instead.
func (*TrackEvent) Descriptor() ([]byte, []int) {
	return file_perfetto_proto_rawDescGZIP(), []int{5}
}

func (x *TrackEvent) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *TrackEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrackEvent) GetType() TrackEvent_Type {
	if x != nil {
		return x.Type
	}
	return TrackEvent_TYPE_UNSPECIFIED
}

func (x *TrackEvent) GetTrackUuid() uint64 {
	if x != nil {
		return x.TrackUuid
	}
	return 0
}

func (x *TrackEvent) GetDebugAnnotations() []*DebugAnnotation {
	if x != nil {
		return x.DebugAnnotations
	}
	return nil
}

// Debug annotation for key-value metadata
// See: https://perfetto.dev/docs/reference/trace-packet-proto
type DebugAnnotation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the annotation (for dictionary entries)
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	// Value - use one of these fields
	//
	// Types that are valid to be assigned to Value:
	//
	//	*DebugAnnotation_BoolValue
	//	*DebugAnnotation_UintValue
	//	*DebugAnnotation_IntValue
	//	*DebugAnnotation_DoubleValue
	//	*DebugAnnotation_StringValue
	//	*DebugAnnotation_PointerValue
	Value isDebugAnnotation_Value `protobuf_oneof:"value"`
	// Nested structures
	DictEntries   []*DebugAnnotation `protobuf:"bytes,11,rep,name=dict_entries,json=dictEntries,proto3" json:"dict_entries,omitempty"`
	ArrayValues   []*DebugAnnotation `protobuf:"bytes,12,rep,name=array_values,json=arrayValues,proto3" json:"array_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugAnnotation) Reset() {
	*x = DebugAnnotation{}
	mi := &file_perfetto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugAnnotation) ProtoMessage() {}

func (x *DebugAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_perfetto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugAnnotation.ProtoReflect.Descriptor instead.
func (*DebugAnnotation) Descriptor() ([]byte, []int) {
	return file_perfetto_proto_rawDescGZIP(), []int{6}
}

func (x *DebugAnnotation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DebugAnnotation) GetValue() isDebugAnnotation_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DebugAnnotation) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*DebugAnnotation_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *DebugAnnotation) GetUintValue() uint64 {
	if x != nil {
		if x, ok := x.Value.(*DebugAnnotation_UintValue); ok {
			return x.UintValue
		}
	}
	return 0
}

func (x *DebugAnnotation) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*DebugAnnotation_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *DebugAnnotation) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*DebugAnnotation_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *DebugAnnotation) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*DebugAnnotation_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *DebugAnnotation) GetPointerValue() uint64 {
	if x != nil {
		if x, ok := x.Value.(*DebugAnnotation_PointerValue); ok {
			return x.PointerValue
		}
	}
	return 0
}

func (x *DebugAnnotation) GetDictEntries() []*DebugAnnotation {
	if x != nil {
		return x.DictEntries
	}
	return nil
}

func (x *DebugAnnotation) GetArrayValues() []*DebugAnnotation {
	if x != nil {
		return x.ArrayValues
	}
	return nil
}

type isDebugAnnotation_Value interface {
	isDebugAnnotation_Value()
}

type DebugAnnotation_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type DebugAnnotation_UintValue struct {
	UintValue uint64 `protobuf:"varint,3,opt,name=uint_value,json=uintValue,proto3,oneof"`
}

type DebugAnnotation_IntValue struct {
	IntValue int64 `protobuf:"varint,4,opt,name=int_value,json=intValue,proto3,oneof"`
}

type DebugAnnotation_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type DebugAnnotation_StringValue struct {
	StringValue string `protobuf:"bytes,6,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type DebugAnnotation_PointerValue struct {
	PointerValue uint64 `protobuf:"varint,7,opt,name=pointer_value,json=pointerValue,proto3,oneof"`
}

func (*DebugAnnotation_BoolValue) isDebugAnnotation_Value() {}

func (*DebugAnnotation_UintValue) isDebugAnnotation_Value() {}

func (*DebugAnnotation_IntValue) isDebugAnnotation_Value() {}

func (*DebugAnnotation_DoubleValue) isDebugAnnotation_Value() {}

func (*DebugAnnotation_StringValue) isDebugAnnotation_Value() {}

func (*DebugAnnotation_PointerValue) isDebugAnnotation_Value() {}

var File_perfetto_proto protoreflect.FileDescriptor

const file_perfetto_proto_rawDesc = "" +
	"\n" +
	"\x0eperfetto.proto\x12\x0fperfetto.protos\"=\n" +
	"\x05Trace\x124\n" +
	"\x06packet\x18\x01 \x03(\v2\x1c.perfetto.protos.TracePacketR\x06packet\"\xff\x01\n" +
	"\vTracePacket\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x04R\ttimestamp\x12;\n" +
	"\x1atrusted_packet_sequence_id\x18\n" +
	" \x01(\rR\x17trustedPacketSequenceId\x12M\n" +
	"\x10track_descriptor\x18< \x01(\v2 .perfetto.protos.TrackDescriptorH\x00R\x0ftrackDescriptor\x12>\n" +
	"\vtrack_event\x18\v \x01(\v2\x1b.perfetto.protos.TrackEventH\x00R\n" +
	"trackEventB\x06\n" +
	"\x04data\"\xd3\x01\n" +
	"\x0fTrackDescriptor\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\x04R\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12<\n" +
	"\aprocess\x18\x03 \x01(\v2\".perfetto.protos.ProcessDescriptorR\aprocess\x129\n" +
	"\x06thread\x18\x04 \x01(\v2!.perfetto.protos.ThreadDescriptorR\x06thread\x12\x1f\n" +
	"\vparent_uuid\x18\x05 \x01(\x04R\n" +
	"parentUuid\"H\n" +
	"\x11ProcessDescriptor\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12!\n" +
	"\fprocess_name\x18\x06 \x01(\tR\vprocessName\"W\n" +
	"\x10ThreadDescriptor\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x10\n" +
	"\x03tid\x18\x02 \x01(\x05R\x03tid\x12\x1f\n" +
	"\vthread_name\x18\x05 \x01(\tR\n" +
	"threadName\"\xbe\x02\n" +
	"\n" +
	"TrackEvent\x12\x1e\n" +
	"\n" +
	"categories\x18\x16 \x03(\tR\n" +
	"categories\x12\x12\n" +
	"\x04name\x18\x17 \x01(\tR\x04name\x124\n" +
	"\x04type\x18\t \x01(\x0e2 .perfetto.protos.TrackEvent.TypeR\x04type\x12\x1d\n" +
	"\n" +
	"track_uuid\x18\v \x01(\x04R\ttrackUuid\x12M\n" +
	"\x11debug_annotations\x18\x04 \x03(\v2 .perfetto.protos.DebugAnnotationR\x10debugAnnotations\"X\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TYPE_SLICE_BEGIN\x10\x01\x12\x12\n" +
	"\x0eTYPE_SLICE_END\x10\x02\x12\x10\n" +
	"\fTYPE_INSTANT\x10\x03\"\x8a\x03\n" +
	"\x0fDebugAnnotation\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1f\n" +
	"\n" +
	"uint_value\x18\x03 \x01(\x04H\x00R\tuintValue\x12\x1d\n" +
	"\tint_value\x18\x04 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x05 \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\x06 \x01(\tH\x00R\vstringValue\x12%\n" +
	"\rpointer_value\x18\a \x01(\x04H\x00R\fpointerValue\x12C\n" +
	"\fdict_entries\x18\v \x03(\v2 .perfetto.protos.DebugAnnotationR\vdictEntries\x12C\n" +
	"\farray_values\x18\f \x03(\v2 .perfetto.protos.DebugAnnotationR\varrayValuesB\a\n" +
	"\x05valueBAZ?github.com/sonicfromnewyoke/mithril/cmd/trace2perfetto/protob\x06proto3"

var (
	file_perfetto_proto_rawDescOnce sync.Once
	file_perfetto_proto_rawDescData []byte
)

func file_perfetto_proto_rawDescGZIP() []byte {
	file_perfetto_proto_rawDescOnce.Do(func() {
		file_perfetto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_perfetto_proto_rawDesc), len(file_perfetto_proto_rawDesc)))
	})
	return file_perfetto_proto_rawDescData
}

var file_perfetto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_perfetto_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_perfetto_proto_goTypes = []any{
	(TrackEvent_Type)(0),      // 0: perfetto.protos.TrackEvent.Type
	(*Trace)(nil),             // 1: perfetto.protos.Trace
	(*TracePacket)(nil),       // 2: perfetto.protos.TracePacket
	(*TrackDescriptor)(nil),   // 3: perfetto.protos.TrackDescriptor
	(*ProcessDescriptor)(nil), // 4: perfetto.protos.ProcessDescriptor
	(*ThreadDescriptor)(nil),  // 5: perfetto.protos.ThreadDescriptor
	(*TrackEvent)(nil),        // 6: perfetto.protos.TrackEvent
	(*DebugAnnotation)(nil),   // 7: perfetto.protos.DebugAnnotation
}
var file_perfetto_proto_depIdxs = []int32{
	2, // 0: perfetto.protos.Trace.packet:type_name -> perfetto.protos.TracePacket
	3, // 1: perfetto.protos.TracePacket.track_descriptor:type_name -> perfetto.protos.TrackDescriptor
	6, // 2: perfetto.protos.TracePacket.track_event:type_name -> perfetto.protos.TrackEvent
	4, // 3: perfetto.protos.TrackDescriptor.process:type_name -> perfetto.protos.ProcessDescriptor
	5, // 4: perfetto.protos.TrackDescriptor.thread:type_name -> perfetto.protos.ThreadDescriptor
	0, // 5: perfetto.protos.TrackEvent.type:type_name -> perfetto.protos.TrackEvent.Type
	7, // 6: perfetto.protos.TrackEvent.debug_annotations:type_name -> perfetto.protos.DebugAnnotation
	7, // 7: perfetto.protos.DebugAnnotation.dict_entries:type_name -> perfetto.protos.DebugAnnotation
	7, // 8: perfetto.protos.DebugAnnotation.array_values:type_name -> perfetto.protos.DebugAnnotation
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_perfetto_proto_init() }
func file_perfetto_proto_init() {
	if File_perfetto_proto != nil {
		return
	}
	file_perfetto_proto_msgTypes[1].OneofWrappers = []any{
		(*TracePacket_TrackDescriptor)(nil),
		(*TracePacket_TrackEvent)(nil),
	}
	file_perfetto_proto_msgTypes[6].OneofWrappers = []any{
		(*DebugAnnotation_BoolValue)(nil),
		(*DebugAnnotation_UintValue)(nil),
		(*DebugAnnotation_IntValue)(nil),
		(*DebugAnnotation_DoubleValue)(nil),
		(*DebugAnnotation_StringValue)(nil),
		(*DebugAnnotation_PointerValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_perfetto_proto_rawDesc), len(file_perfetto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_perfetto_proto_goTypes,
		DependencyIndexes: file_perfetto_proto_depIdxs,
		EnumInfos:         file_perfetto_proto_enumTypes,
		MessageInfos:      file_perfetto_proto_msgTypes,
	}.Build()
	File_perfetto_proto = out.File
	file_perfetto_proto_goTypes = nil
	file_perfetto_proto_depIdxs = nil
}
