// Code generated by syscalls_gen syscalls.go or go generate. Manual edits may be overwritten.

package sealevel

import (
	"github.com/Overclock-Validator/mithril/pkg/features"
	"github.com/Overclock-Validator/mithril/pkg/sbpf"
)

const (
	hash_abort                                 = 0xb6fc1a11
	hash_sol_panic_                            = 0x686093bb
	hash_sol_log_                              = 0x207559bd
	hash_sol_log_64_                           = 0x5c2a3178
	hash_sol_log_pubkey                        = 0x7ef088ca
	hash_sol_log_compute_units_                = 0x52ba5096
	hash_sol_log_data                          = 0x7317b434
	hash_sol_sha256                            = 0x11f49d86
	hash_sol_keccak256                         = 0xd7793abb
	hash_sol_blake3                            = 0x174c5122
	hash_sol_secp256k1_recover                 = 0x17e40350
	hash_sol_big_mod_exp                       = 0x780e4c15
	hash_sol_poseidon                          = 0xc4947c21
	hash_sol_remaining_compute_units           = 0xedef5aee
	hash_sol_curve_validate_point              = 0xaa2607ca
	hash_sol_curve_multiscalar_mul             = 0x60a40880
	hash_sol_curve_group_op                    = 0xdd1c41a6
	hash_sol_curve_decompress                  = 0x80c98b0
	hash_sol_curve_pairing_map                 = 0xf111a47e
	hash_sol_alt_bn128_compression             = 0x334fd5ed
	hash_sol_alt_bn128_group_op                = 0xae0c318b
	hash_sol_memcpy_                           = 0x717cc4a3
	hash_sol_memcmp_                           = 0x5fdcde31
	hash_sol_memset_                           = 0x3770fb22
	hash_sol_memmove_                          = 0x434371f8
	hash_sol_alloc_free_                       = 0x83f00e8f
	hash_sol_create_program_address            = 0x9377323c
	hash_sol_try_find_program_address          = 0x48504a38
	hash_sol_get_stack_height                  = 0x85532d94
	hash_sol_get_return_data                   = 0x5d2245e4
	hash_sol_set_return_data                   = 0xa226d3eb
	hash_sol_get_processed_sibling_instruction = 0xadb8efc8
	hash_sol_get_clock_sysvar                  = 0xd56b5fe9
	hash_sol_get_rent_sysvar                   = 0xbf7188f6
	hash_sol_get_epoch_schedule_sysvar         = 0x23a29a61
	hash_sol_get_epoch_rewards_sysvar          = 0xfdba2b3b
	hash_sol_get_last_restart_slot             = 0x188a0031
	hash_sol_invoke_signed_c                   = 0xa22b9c85
	hash_sol_invoke_signed_rust                = 0xd7449092
	hash_sol_get_sysvar                        = 0x13c1b505
	hash_sol_get_epoch_stake                   = 0x5be92f4a
)

func Syscalls(ft *features.Features, isDeploy bool, h uint32) (f sbpf.Syscall, ok bool) {
	ok = true
	switch h {
	case hash_abort:
		f = SyscallAbort
	case hash_sol_panic_:
		f = SyscallPanic
	case hash_sol_log_:
		f = SyscallLog
	case hash_sol_log_64_:
		f = SyscallLog64
	case hash_sol_log_pubkey:
		f = SyscallLogPubkey
	case hash_sol_log_compute_units_:
		f = SyscallLogCUs
	case hash_sol_log_data:
		f = SyscallLogData
	case hash_sol_sha256:
		f = SyscallSha256
	case hash_sol_keccak256:
		f = SyscallKeccak256
	case hash_sol_blake3:
		f = SyscallBlake3
		ok = ft.IsActive(features.Blake3SyscallEnabled)
	case hash_sol_secp256k1_recover:
		f = SyscallSecp256k1Recover
	// PINNED to the agave-syscalls-4.0.0 / solana-big-mod-exp-3.0.0
	// implementation this fork targets. The gate
	// EBq48m8irRKuE7ZnMTLvLg2UuGSqhe8s8oMqnmja1fJw is inactive on mainnet as of
	// 2026-07, but agave master has replaced the body with an Ok(1) no-op stub
	// pending SIMD-0529: if this gate ever activates on mainnet, the
	// implementation behind SyscallBigModExp MUST be revisited before the
	// activation epoch or the node will fork. See the comment on
	// SyscallBigModExpImpl in syscalls_big_mod_exp.go.
	case hash_sol_big_mod_exp:
		f = SyscallBigModExp
		ok = ft.IsActive(features.EnableBigModExpSyscall)
	case hash_sol_poseidon:
		f = SyscallPoseidon
	case hash_sol_remaining_compute_units:
		f = SyscallRemainingComputeUnits
		ok = ft.IsActive(features.RemainingComputeUnitsSyscallEnabled)
	case hash_sol_curve_validate_point:
		f = SyscallValidatePoint
		ok = ft.IsActive(features.Curve25519SyscallEnabled)
	case hash_sol_curve_multiscalar_mul:
		f = SyscallCurveMultiscalarMultiplication
		ok = ft.IsActive(features.Curve25519SyscallEnabled)
	case hash_sol_curve_group_op:
		f = SyscallCurveGroupOps
		ok = ft.IsActive(features.Curve25519SyscallEnabled)
	case hash_sol_curve_decompress:
		f = SyscallCurveDecompress
		ok = ft.IsActive(features.EnableBls12_381Syscall)
	case hash_sol_curve_pairing_map:
		f = SyscallCurvePairingMap
		ok = ft.IsActive(features.EnableBls12_381Syscall)
	case hash_sol_alt_bn128_compression:
		f = SyscallAltBn128Compression
		ok = ft.IsActive(features.EnableAltbn128CompressionSyscall)
	case hash_sol_alt_bn128_group_op:
		f = SyscallAltBn128
		ok = ft.IsActive(features.EnableAltBn128Syscall)
	case hash_sol_memcpy_:
		f = SyscallMemcpy
	case hash_sol_memcmp_:
		f = SyscallMemcmp
	case hash_sol_memset_:
		f = SyscallMemset
	case hash_sol_memmove_:
		f = SyscallMemmove
	case hash_sol_alloc_free_:
		f = SyscallAllocFree
		ok = !isDeploy
	case hash_sol_create_program_address:
		f = SyscallCreateProgramAddress
	case hash_sol_try_find_program_address:
		f = SyscallTryFindProgramAddress
	case hash_sol_get_stack_height:
		f = SyscallGetStackHeight
	case hash_sol_get_return_data:
		f = SyscallGetReturnData
	case hash_sol_set_return_data:
		f = SyscallSetReturnData
	case hash_sol_get_processed_sibling_instruction:
		f = SyscallGetProcessedSiblingInstruction
	case hash_sol_get_clock_sysvar:
		f = SyscallGetClockSysvar
	case hash_sol_get_rent_sysvar:
		f = SyscallGetRentSysvar
	case hash_sol_get_epoch_schedule_sysvar:
		f = SyscallGetEpochScheduleSysvar
	case hash_sol_get_epoch_rewards_sysvar:
		f = SyscallGetEpochRewardsSysvar
		ok = ft.IsActive(features.EnablePartitionedEpochReward) || ft.IsActive(features.EnablePartitionedEpochRewardsSuperfeature)
	case hash_sol_get_last_restart_slot:
		f = SyscallGetLastRestartSlotSysvar
		ok = ft.IsActive(features.LastRestartSlotSysvar)
	case hash_sol_invoke_signed_c:
		f = sbpf.SyscallFunc5(SyscallInvokeSignedCImpl)
	case hash_sol_invoke_signed_rust:
		f = sbpf.SyscallFunc5(SyscallInvokeSignedRustImpl)
	case hash_sol_get_sysvar:
		f = SyscallGetSysvar
		ok = ft.IsActive(features.GetSysvarSyscallEnabled)
	case hash_sol_get_epoch_stake:
		f = SyscallGetEpochStake
		ok = ft.IsActive(features.EnableGetEpochStakeSyscall)
	default:
		ok = false
	}
	return
}
